package org.comdnmr.modelfree;

/**
 * Abstract base for weight-based bootstrap samplers.
 *
 * <p>Instead of perturbing observed values, a {@code WeightSampler} assigns a
 * non-negative weight to each spectral-density observation. The weights are
 * generated by the concrete subclass's {@link #sampleWeights()} and stored on the
 * underlying {@link MolDataValues} via {@link MolDataValues#weight(double[])}.
 *
 * <p>{@link #getOriginalData()} resets all weights to 1.0, restoring uniform
 * weighting equivalent to an unperturbed fit.
 *
 * @see NonparametricSampler
 * @see BayesianSampler
 */
public abstract class WeightSampler extends BootstrapSampler {

    WeightSampler(MolDataValues data) { super(data); }

    /**
     * Generates a weight vector for the next bootstrap replicate.
     *
     * <p>The returned array must have length {@link #getNValues()}. Each element
     * gives the weight of the corresponding J(ω) observation; the classical bootstrap
     * uses integer counts, while the Bayesian bootstrap uses positive real values.
     *
     * @return per-observation bootstrap weights
     */
    protected abstract double[] sampleWeights();

    /**
     * {@inheritDoc}
     *
     * <p>Delegates to {@link #sampleWeights()} and stores the result on the wrapped
     * data via {@link MolDataValues#weight(double[])}.
     */
    public MolDataValues sample() {
        double[] weights = sampleWeights();
        data.weight(weights);
        return data;
    }

    /**
     * {@inheritDoc}
     *
     * <p>Resets all observation weights to 1.0, restoring the unweighted state.
     */
    public MolDataValues getOriginalData() {
        int nJ = getNValues();
        double[] weights = new double[nJ];
        for (int j = 0; j < nJ; j++) weights[j] = 1.0;
        data.weight(weights);
        return data;
    }

}
